### ISSUE TITLE
Account Linking

### ISSUE THREAD

**Issue by boonsboos** [monkegame/monkebotJ#1]
While having a global and per map leaderboard is very cool, it might be worth it to have personal stats as well. 

# TODO
- [x] setup account linking
- [x] shove it in a database
- [x] somehow retrieve info on request
- [x] put it in a nice embed
- [x] ???????
- [x] profit 

I hope to be able to get this done in the next couple of weeks.

**Comment by boonsboos** [comment]
added in v1.1

**Comment by boonsboos** [comment]
fun fact: this didn't take weeks, only like 3-4 hrs
